-- MaredeVendas — Setup completo do banco
-- Execute os arquivos em migrations/ NA ORDEM NUMÉRICA no SQL Editor do Supabase:
--
--   001_initial_schema.sql
--   002_storage_and_policies.sql
--   003_customer_profile.sql
--   004_store_subscriptions.sql
--   005_fix_signup_and_admin_bruno.sql
--   006_store_theme_color.sql
--   007_admin_user_passwords.sql
--   008_product_price_cooldown.sql
--   009_marketplace_visibility.sql
--   010_store_ads.sql
--   011_product_engagement.sql
--   012_demo_stores.sql
--
-- Após rodar as migrations (recomendado via CLI):
--   npx supabase login
--   npx supabase link --project-ref ulpjsxmilumqedkkfuqw
--   npx supabase db push
--
-- Ou cole cada arquivo no SQL Editor do dashboard.
--
-- Depois:
-- 1. Authentication → URL Configuration → Site URL e Redirect URLs:
--    https://kelfys.github.io/MaredeVendas-vanilla/
--    http://localhost:8080
-- 2. Credenciais do frontend em js/config.js (SUPABASE_URL + SUPABASE_ANON_KEY)
-- 3. Crie usuários admin/lojista no Auth; migration 005 promove brunopdearaujo@gmail.com a admin

SELECT 'Migrations aplicadas. Configure Auth URLs e js/config.js.' AS instrucao;