/**
 * Textos estáticos da interface — edite em strings-editor.html
 * Uso: import { t } from './strings.js?v=3788780'  →  t('nav.home')
 */

export const STRINGS = {
  "app": {
    "name": "MaredeVendas",
    "nameAccent": "Vendas",
    "pageTitle": "MaredeVendas — Seu shopping online local",
    "metaDescription": "Seu shopping online de lojas perto de você. Explore, monte o carrinho e peça pelo WhatsApp — rápido e sem complicação.",
    "loadErrorTitle": "Erro ao carregar",
    "loadErrorBody": "Tente abrir a página inicial e navegar pelo menu.",
    "loadErrorHomeLink": "página inicial",
    "selectPlaceholder": "Selecione...",
    "sponsored": "Patrocinado",
    "freePlanPrice": "Grátis",
    "perMonth": "/mês",
    "noImage": "Sem imagem",
    "dashPlaceholder": "—",
    "scrollToTop": "Voltar ao topo"
  },
  "nav": {
    "home": "Início",
    "createStore": "Criar loja",
    "login": "Entrar",
    "logout": "Sair",
    "myAccount": "👤 Minha conta",
    "backToSite": "← Voltar ao site",
    "toggleTheme": "Alternar tema",
    "openMenu": "☰",
    "closeMenu": "✕",
    "refresh": "↻ Atualizar",
    "staffOverview": "Visão Geral",
    "staffStores": "Lojas",
    "staffProducts": "Produtos",
    "staffAds": "Anúncios",
    "staffOrders": "Pedidos",
    "staffApprovals": "Aprovações",
    "staffReports": "Denúncias",
    "staffNeighborhoods": "Bairros",
    "staffCategories": "Categorias",
    "staffModerators": "Moderadores",
    "staffProfiles": "Perfis",
    "staffStringsEditor": "Editor de textos",
    "staffAccount": "Minha Conta",
    "merchantCatalog": "Catálogo",
    "merchantAds": "Anúncios",
    "merchantPlans": "Planos",
    "merchantSettings": "Configurações",
    "customerOverview": "Início",
    "customerFavorites": "Favoritos",
    "customerLiked": "Curtidos",
    "customerOrders": "Pedidos",
    "customerProfile": "Perfil",
    "merchantPanel": "Painel do Lojista",
    "adminPanel": "Painel Admin",
    "merchantOverview": "Visão Geral"
  },
  "home": {
    "heroEyebrow": "Seu shopping online",
    "heroTitle": "Lojas perto de você, na palma da mão",
    "heroStats": "{stores} lojas · {products} produtos neste bairro",
    "heroStatsStoresOnly": "{stores} lojas neste bairro",
    "clearFilters": "Limpar busca",
    "neighborhoodsLabel": "Bairro",
    "categoriesLabel": "Categoria",
    "searchStoresProducts": "O que você procura?",
    "searchAds": "Buscar oferta...",
    "allCategories": "Todas",
    "allNeighborhoods": "Todos",
    "allNeighborhoodsLabel": "Todos os bairros",
    "heroStatsAll": "{stores} lojas · {products} produtos",
    "heroStatsStoresOnlyAll": "{stores} lojas",
    "tabFeed": "Para você",
    "tabAds": "Ofertas",
    "viewStoreCta": "Ver loja e pedir no WhatsApp",
    "viewStore": "Ver loja",
    "badgeMostLiked": "Mais curtido",
    "badgeNewProduct": "Novidade",
    "badgeFeatured": "Destaque",
    "addToCartShort": "+ Carrinho",
    "connectErrorTitle": "Erro ao conectar",
    "noNeighborhoodsTitle": "Nenhum bairro por aqui ainda",
    "noNeighborhoodsBody": "Em breve novas regiões entram no seu shopping online.",
    "noAdsTitle": "Sem ofertas no momento",
    "noAdsBody": "Volte em breve — novas promoções das lojas do bairro chegam aqui.",
    "emptyFeedTitle": "Ainda quieto neste bairro",
    "emptyFeedBody": "Em breve lojas e produtos aparecem aqui. Explore outro bairro ou volte já já.",
    "nothingFoundTitle": "Nada por aqui",
    "nothingFoundBody": "Tente outra categoria, outro termo ou limpe a busca.",
    "noAdsFoundTitle": "Nenhuma oferta encontrada",
    "noAdsFoundBody": "Tente outra palavra ou limpe a busca.",
    "resultsFor": "Resultados para \"{term}\"",
    "adsFor": "Ofertas para \"{term}\"",
    "neighborhoodLabel": "Bairro: {name}"
  },
  "auth": {
    "loginTitle": "Entrar",
    "loginDescription": "Use o mesmo login para conta de cliente ou lojista.",
    "loginWithGoogle": "Entrar com Google",
    "dividerOrEmail": "ou use email e senha",
    "dividerOrForm": "ou preencha o formulário",
    "submitLogin": "Entrar",
    "forgotPassword": "Esqueci minha senha",
    "createCustomerAccount": "Criar conta de cliente",
    "registerMyStore": "Cadastrar minha loja",
    "adminAccess": "Acesso admin",
    "moderatorAccess": "Acesso moderador",
    "registerTitle": "Criar Conta",
    "registerDescription": "Cadastre-se para favoritar lojas e agilizar seus pedidos.",
    "registerWithGoogle": "Criar conta com Google",
    "submitRegister": "Criar conta",
    "alreadyHaveAccount": "Já tenho conta",
    "adminLoginTitle": "Painel Admin",
    "adminLoginDescription": "Acesso restrito a administradores da plataforma.",
    "moderatorLoginTitle": "Painel Moderador",
    "moderatorLoginDescription": "Acesso restrito a moderadores da plataforma.",
    "accessDenied": "Acesso negado.",
    "resetEmailFirst": "Informe seu email acima primeiro.",
    "resetLinkSent": "Link de redefinição enviado para seu email.",
    "registerStoreTitle": "Cadastrar Loja",
    "registerStoreAccountFirst": "Primeiro crie sua conta de lojista.",
    "registerStoreWithGoogle": "Cadastrar loja com Google",
    "createMerchantAccount": "Criar conta de lojista",
    "registerStoreFormDescription": "Preencha os dados da sua loja. Após envio, aguarde aprovação do moderador da região.",
    "storeName": "Nome da loja",
    "neighborhoodRegion": "Bairro / região",
    "submitStoreRegistration": "Enviar cadastro",
    "storeSubmittedSuccess": "Loja enviada! Aguarde aprovação.",
    "rulesShow": "Ver regras e planos da plataforma",
    "rulesHide": "Ocultar regras e planos",
    "registerGoogleHint": "Rápido e seguro — sua conta será de cliente.",
    "deliveryPeriodLabel": "Melhor horário para entrega",
    "openingHoursLabel": "Horário de funcionamento",
    "whatsappWithDdd": "WhatsApp (com DDD)",
    "merchantSignupHint": "Conta de lojista — em seguida você preenche os dados da loja.",
    "accessDeniedTitle": "Acesso negado",
    "notMerchantAccount": "Conta não é de lojista.",
    "alreadyHasStore": "Você já tem uma loja",
    "goToPanel": "Ir ao painel",
    "accountLoadError": "Não foi possível carregar sua conta.",
    "storeStatusLine": "Status: {status}",
    "openingHoursPlaceholder": "Seg-Sex 9h-18h",
    "neighborhoodAdminOnlyHint": "Escolha um bairro cadastrado pelo admin. Cidade e UF vêm automaticamente.",
    "categoryAdminOnlyHint": "Escolha uma categoria (tipo) criada pelo admin.",
    "cityFromNeighborhood": "Preenchida pelo bairro",
    "noNeighborhoodsAvailable": "Nenhum bairro disponível no momento. Peça ao admin para cadastrar regiões.",
    "noCategoriesAvailable": "Nenhuma categoria disponível no momento. Peça ao admin para cadastrar os tipos."
  },
  "store": {
    "unavailableTitle": "Loja indisponível",
    "unavailableBody": "Esta loja não existe, não foi aprovada ou está com assinatura inativa.",
    "backToHome": "Voltar ao início",
    "cart": "🛒 Carrinho",
    "favorited": "❤️ Favoritado",
    "favorite": "🤍 Favoritar",
    "share": "🔗 Compartilhar",
    "productsAndServices": "Produtos e serviços",
    "storeReviews": "Avaliações da loja",
    "unavailable": "Indisponível",
    "addProduct": "+ Adicionar",
    "loginToLike": "Entre para curtir",
    "noCommentsYet": "Nenhum comentário ainda.",
    "commentPlaceholder": "Escreva um comentário...",
    "submitComment": "Comentar",
    "linkCopiedToast": "Link copiado!",
    "commentPublished": "Comentário publicado!",
    "backShort": "← Voltar",
    "productsSortHint": "Ordenados por popularidade — os mais curtidos aparecem com mais destaque.",
    "emptyCatalog": "Nenhum item disponível no catálogo",
    "loginToEngage": "Entre na sua conta para curtir ou comentar.",
    "customersOnlyFavorite": "Apenas clientes podem favoritar lojas.",
    "commentsLoadError": "Erro ao carregar comentários.",
    "likeError": "Não foi possível curtir este produto.",
    "commentError": "Não foi possível publicar o comentário.",
    "engagementTitle": "Popularidade",
    "engagementHint": "Clientes que favoritaram a loja e curtidas nos produtos do catálogo."
  },
  "engagement": {
    "statsAria": "Estatísticas de engajamento",
    "profileActivity": "Sua atividade",
    "storeFavoriteOne": "favorito",
    "storeFavorites": "favoritos",
    "storeLikeOne": "curtida nos produtos",
    "storeLikes": "curtidas nos produtos",
    "customerFavoriteOne": "loja favorita",
    "customerFavorites": "lojas favoritas",
    "customerLikeOne": "produto curtido",
    "customerLikes": "produtos curtidos"
  },
  "cart": {
    "title": "Carrinho",
    "yourOrder": "Seu pedido",
    "emptyTitle": "Carrinho vazio",
    "emptyBody": "Adicione produtos de uma loja para começar seu pedido.",
    "itemsCount": "Itens ({count})",
    "total": "Total",
    "checkoutHint": "Pagamento combinado com a loja via WhatsApp"
  },
  "checkout": {
    "finalizeOrder": "Finalizar pedido",
    "paymentLegend": "Como você prefere pagar?",
    "deliverySectionTitle": "Dados para entrega",
    "orderTotal": "Total do pedido",
    "back": "Voltar",
    "sendViaWhatsapp": "Enviar via WhatsApp",
    "paymentPix": "PIX",
    "paymentPixHint": "A loja envia a chave no WhatsApp",
    "paymentCash": "Dinheiro na entrega",
    "paymentCashHint": "Pague ao receber o pedido",
    "paymentCard": "Cartão na entrega",
    "paymentCardHint": "Maquininha ou cartão com a loja",
    "paymentTransfer": "Transferência",
    "paymentTransferHint": "Dados bancários no WhatsApp",
    "namePlaceholder": "Seu nome completo",
    "addressPlaceholder": "Rua, número, bairro, complemento",
    "submitting": "Enviando...",
    "storeNoWhatsapp": "Esta loja ainda não recebe pedidos por WhatsApp."
  },
  "customer": {
    "loginRequiredTitle": "Faça login",
    "loginRequiredBody": "Entre na sua conta para acessar favoritos, pedidos e perfil.",
    "myAccountTitle": "Minha conta",
    "metricFavoriteStores": "Lojas favoritas",
    "metricLikedProducts": "Produtos curtidos",
    "metricOrders": "Pedidos",
    "metricCartItems": "Itens no carrinho",
    "exploreStores": "Explorar lojas",
    "exploreStoresDesc": "Descubra novidades no feed",
    "viewFavorites": "Ver favoritos",
    "openCart": "Abrir carrinho",
    "noFavoriteStoresTitle": "Nenhuma loja favorita",
    "noFavoriteStoresBody": "Abra uma loja e toque no coração para salvar aqui.",
    "noLikedProductsTitle": "Nenhum produto curtido",
    "noLikedProductsBody": "Curta produtos nas vitrines para encontrá-los rapidamente aqui.",
    "noOrdersTitle": "Nenhum pedido ainda",
    "noOrdersBody": "Seus pedidos feitos pela plataforma aparecerão aqui após o checkout.",
    "profileUpdated": "Perfil atualizado",
    "passwordUpdated": "Senha atualizada",
    "savedStoresHint": "Salve lojas que gostar",
    "savedStoresCount": "{count} loja(s) salva(s)",
    "cartItemsHint": "{count} item(ns) · {store}",
    "recentFavorites": "Lojas favoritas recentes",
    "viewAllFeminine": "Ver todas",
    "likedProductsSection": "Produtos curtidos",
    "viewAllMasculine": "Ver todos",
    "greeting": "Olá, {name}!",
    "emptyOverviewBody": "Explore lojas no início, favorite as que mais gostar e curta produtos para montar sua lista.",
    "goToHome": "Ir para o início",
    "viewProducts": "Ver produtos",
    "placeOrder": "Fazer um pedido",
    "paymentLabel": "Pagamento:",
    "deliveryPeriodPreferred": "Horário preferido de entrega",
    "saveProfile": "Salvar perfil",
    "changePasswordTitle": "Alterar senha",
    "passwordHint": "Use uma senha forte com pelo menos 8 caracteres.",
    "updatePassword": "Atualizar senha",
    "passwordsMismatch": "As senhas não coincidem",
    "loadError": "Erro ao carregar dados",
    "saveProfileError": "Erro ao salvar perfil",
    "updatePasswordError": "Erro ao atualizar senha",
    "tabOverview": "Visão geral",
    "tabFavorites": "Lojas favoritas",
    "tabLiked": "Produtos curtidos",
    "tabOrders": "Meus pedidos",
    "tabProfile": "Meu perfil",
    "defaultName": "cliente",
    "accountSectionsAria": "Seções da conta"
  },
  "common": {
    "preview": "Prévia",
    "yes": "Sim",
    "no": "Não",
    "saving": "Salvando...",
    "sending": "Enviando...",
    "all": "Todos",
    "active": "Ativo",
    "inactive": "Inativo",
    "activePlural": "Ativos",
    "inactivePlural": "Inativos",
    "manage": "Gerenciar",
    "configure": "Configurar",
    "register": "Cadastrar",
    "viewAll": "Ver todos",
    "viewProducts": "Ver produtos",
    "viewPlans": "Ver planos",
    "noResults": "Nenhum resultado",
    "anonymous": "Anônimo",
    "completed": "Concluído",
    "date": "Data",
    "customer": "Cliente",
    "payment": "Pagamento",
    "total": "Total",
    "image": "Imagem",
    "price": "Preço",
    "stock": "Estoque",
    "item": "Item",
    "title": "Título",
    "message": "Mensagem",
    "from": "De",
    "to": "Para",
    "account": "Conta",
    "noCategory": "Sem categoria",
    "priceWithCurrency": "Preço (R$)",
    "totalWithCurrency": "Total (R$)",
    "id": "ID",
    "or": "ou",
    "sortByName": "Ordenar por nome",
    "sortByPrice": "Ordenar por preço",
    "sortByStock": "Ordenar por estoque",
    "sortByDateRecent": "Ordenar por data, mais recentes primeiro",
    "sortByDateOldest": "Ordenar por data, mais antigos primeiro",
    "exportCsv": "⬇ Exportar CSV",
    "activate": "Ativar",
    "allFeminine": "Todas",
    "creating": "Criando...",
    "days7": "7 dias",
    "days30": "30 dias",
    "months12": "12 meses",
    "deactivate": "Desativar",
    "last7Days": "Últimos 7 dias",
    "neighborhood": "Bairro",
    "noOrdersFilter": "Nenhum pedido corresponde aos filtros selecionados.",
    "ordersExported": "{count} pedido(s) exportado(s)",
    "pendingSingular": "pendente",
    "pendingPlural": "pendentes",
    "period": "Período",
    "product": "Produto",
    "since": "Desde",
    "slug": "Slug",
    "store": "Loja",
    "today": "Hoje",
    "view": "Ver",
    "refreshDataTitle": "Atualizar dados",
    "loadingComments": "Carregando comentários...",
    "defaultUser": "Usuário",
    "defaultStore": "Loja",
    "closeCart": "Fechar carrinho",
    "showPassword": "Mostrar senha",
    "hidePassword": "Ocultar senha",
    "removeItem": "Remover item",
    "decreaseQty": "Diminuir quantidade",
    "increaseQty": "Aumentar quantidade",
    "priceEach": "{price} cada",
    "loginOrRegisterToComment": "<a href=\"#/conta/entrar\">Entre</a> ou <a href=\"#/conta/criar\">crie uma conta</a> para comentar.",
    "passwordMismatch": "As senhas não coincidem."
  },
  "orderStatus": {
    "pending": "Pendente",
    "sent": "Enviado",
    "viewed": "Visualizado",
    "sentPlural": "Enviados",
    "viewedPlural": "Visualizados",
    "pendingPlural": "Pendentes",
    "sentCount": "{count} enviados",
    "viewedCount": "{count} visualizados"
  },
  "adStatus": {
    "pending": "Aguardando aprovação",
    "approved": "Ativo",
    "rejected": "Rejeitado",
    "expired": "Expirado"
  },
  "merchant": {
    "restrictedAccess": "Acesso restrito",
    "noStoreRegistered": "Nenhuma loja cadastrada",
    "statusPending": "Aguardando aprovação",
    "statusApproved": "Loja aprovada",
    "statusBlocked": "Loja bloqueada",
    "viewPublicStore": "Ver loja pública",
    "activeProducts": "Produtos ativos",
    "orders": "Pedidos",
    "settingsSaved": "Configurações salvas!",
    "productUpdated": "Produto atualizado!",
    "newAd": "Novo anúncio",
    "plansSubtitle": "Assine ou renove o plano da sua loja ou serviço",
    "saveChanges": "Salvar alterações",
    "completeRegistrationHint": "Complete o cadastro para acessar o painel.",
    "yourStore": "Sua loja",
    "registerStoreSubtitle": "Cadastre sua loja para começar a vender",
    "orderVolume": "Volume de pedidos",
    "views": "Visualizações",
    "viewsThisWeek": " · {count} na semana",
    "viewPlansCta": "Ver planos",
    "productsTitle": "Produtos",
    "manageCatalog": "Gerenciar catálogo",
    "viewRequests": "Ver solicitações",
    "adsTitle": "Anúncios",
    "promoteInFeed": "Divulgar no feed",
    "plansTitle": "Planos",
    "subscribeOrRenew": "Assinar ou renovar",
    "settingsTitle": "Configurações",
    "storeData": "Dados da loja",
    "storefront": "Vitrine",
    "viewAsCustomer": "Ver como cliente",
    "afterApproval": "Após aprovação",
    "whatsappFilled": "WhatsApp preenchido",
    "threeActiveItems": "Pelo menos 3 itens ativos no catálogo",
    "storeApprovedByAdmin": "Loja aprovada pelo admin",
    "underReview": "Em análise",
    "firstSteps": "Primeiros passos",
    "stepsCompleted": "{done}/{total} concluídos",
    "recentOrders": "Pedidos recentes",
    "noOrdersYetBody": "Quando clientes pedirem pelo WhatsApp, os pedidos aparecerão aqui.",
    "lowStock": "Estoque baixo",
    "unitsShort": "{count} un.",
    "reviews": "Avaliações",
    "noReviewsTitle": "Nenhuma avaliação",
    "noReviewsBody": "Quando clientes avaliarem sua loja, as notas aparecerão aqui.",
    "ratingSingular": "avaliação",
    "ratingPlural": "avaliações",
    "noAdsBody": "Crie anúncios para aparecer no feed principal do marketplace.",
    "adActiveOne": "{count} ativo",
    "adActiveMany": "{count} ativos",
    "adPendingOne": "{count} pendente",
    "adPendingMany": "{count} pendentes",
    "adsTotal": "{count} no total",
    "priceChangeInterval": "No seu plano, o preço pode ser alterado a cada {hours}h.",
    "priceCooldownWait": "Aguarde {remaining} para alterar o preço novamente.",
    "noPriceChanges": "Nenhuma alteração de preço registrada.",
    "viewPlansLink": "Ver planos",
    "markAsViewed": "Marcar como visto",
    "adCreatedAt": "Criado em {date}",
    "adExpiresAt": " · Expira em {date}",
    "storeImage": "Imagem da loja",
    "storeLogo": "Logo da loja (foto de perfil)",
    "removeLogo": "Remover logo atual",
    "storeBanner": "Banner da loja",
    "removeBanner": "Remover banner atual",
    "viewPlansUpgrade": "Ver planos e fazer upgrade",
    "bannerReadonlyHint": "Banner atual (somente leitura no plano Gratuito):",
    "planChangePending": "Pedido de mudança para <strong>{planName}</strong> aguardando aprovação desde {date}. Loja: <strong>{storeName}</strong> · ID: <code>{storeId}</code>.",
    "activePlan": "Plano ativo",
    "storeLabel": "Loja: {name}",
    "planStoreId": "ID da loja: {storeId}",
    "storeApprovedBadge": "Loja aprovada",
    "howToSubscribe": "Como assinar ou renovar:",
    "subscribeStep1": "Realize o pagamento do plano escolhido.",
    "subscribeStep2": "Clique em <strong>Solicitar</strong> no card do plano para enviar o pedido ao administrador.",
    "subscribeStep3": "Use o botão do WhatsApp para enviar o comprovante com o <strong>ID da loja</strong> e o nome da loja.",
    "subscribeStep4": "Após aprovação, o plano é ativado automaticamente na sua conta.",
    "planLimitsQuestion": "Dúvidas sobre limites?",
    "readRules": "Leia as regras",
    "manageYourPlan": "gerencie seu plano",
    "planRenewal": "renovação",
    "planUpgradeTo": "upgrade para {planName}",
    "confirmPlanRequest": "Enviar pedido de {action}?",
    "planRequestSent": "Pedido enviado! Loja: {storeName} · ID: {storeId}. Aguarde aprovação do administrador.",
    "planSummary": "Plano {planName} · {price}",
    "viewStorefront": "Ver vitrine",
    "subscribeOrUpgrade": "Assinar ou fazer upgrade",
    "noOrdersExport": "Nenhum pedido para exportar",
    "ordersExported": "{count} pedido(s) exportado(s)",
    "priceHistory": "Histórico de preços",
    "loadingPriceHistory": "Carregando histórico...",
    "confirmDeleteProduct": "Excluir este produto?",
    "productDeleted": "Produto excluído",
    "itemRegistered": "Item cadastrado!",
    "saveProduct": "Salvar produto",
    "selectPaymentMethod": "Selecione pelo menos uma forma de pagamento.",
    "adSentForApproval": "Anúncio enviado para aprovação!",
    "adCreatedWithId": "Anúncio enviado! ID: {id}",
    "extraAdFeeNote": "Você usou os {limit} anúncios inclusos deste mês. Este anúncio extra custa {fee} e fica ativo por {hours}h após aprovação. Ao criar, você receberá um ID — use-o no pagamento pelo WhatsApp.",
    "extraAdFeeAck": "Confirmo a taxa de {fee} e enviarei o comprovante pelo WhatsApp com o ID do anúncio",
    "extraAdPayAfterCreate": "Após clicar em Criar anúncio, copie o ID exibido e use o botão do WhatsApp na lista para enviar o comprovante.",
    "extraAdPaymentBanner": "Anúncio extra criado! Envie o comprovante de {fee} pelo WhatsApp informando o ID:",
    "extraAdSendReceipt": "Enviar comprovante (R$ {fee})",
    "adIdLabel": "ID: {id}",
    "adIdPendingTitle": "ID do anúncio",
    "adIdPendingHint": "Informe este ID ao enviar o comprovante pelo WhatsApp (anúncios extras).",
    "adExtraBadge": "Extra · {fee}",
    "createAd": "Criar anúncio",
    "passwordsMismatch": "As senhas não coincidem.",
    "passwordChangedSuccess": "Senha alterada com sucesso.",
    "changePassword": "Alterar senha",
    "orderMarkedViewed": "Pedido marcado como visualizado",
    "newOrderReceived": "Novo pedido recebido!",
    "catalogItemCount": "{count} item no catálogo",
    "catalogItemsCount": "{count} itens no catálogo",
    "newCatalogItem": "Novo item do catálogo",
    "productNamePlaceholder": "Nome do produto ou serviço",
    "descriptionPlaceholder": "Descrição",
    "newProductPreview": "Novo produto",
    "saveItem": "Salvar item",
    "catalog": "Catálogo",
    "activeItemsCount": "{count} ativos",
    "emptyCatalogTitle": "Catálogo vazio",
    "emptyCatalogBody": "Cadastre seu primeiro produto ou serviço usando o formulário acima.",
    "searchCatalog": "Buscar no catálogo...",
    "noProductsFilter": "Nenhum produto corresponde aos filtros selecionados.",
    "ordersVolumeSummary": "{count} pedido · {revenue} em volume",
    "ordersVolumeSummaryPlural": "{count} pedidos · {revenue} em volume",
    "sentOrdersCount": "{count} enviados",
    "viewedOrdersCount": "{count} visualizados",
    "pendingOrdersCount": "{count} pendentes",
    "noOrdersTitle": "Nenhum pedido",
    "noOrdersBody": "Os pedidos feitos pelo WhatsApp aparecerão aqui automaticamente.",
    "searchCustomerPhone": "Buscar cliente ou telefone...",
    "noOrdersFilter": "Nenhum pedido corresponde aos filtros selecionados.",
    "exportFilteredHint": "Exporta todos os pedidos filtrados (todas as páginas)",
    "adsSubtitle": "Divulgue sua loja no feed principal",
    "adsAfterApproval": "Disponível após aprovação da loja",
    "adsApprovalRequired": "Sua loja precisa estar aprovada e com assinatura ativa para criar anúncios.",
    "adsPremiumRequired": "Anúncios no feed são exclusivos do plano Premium (até 2 por mês).",
    "adTitlePlaceholder": "Ex: Promoção de fim de semana",
    "adMessagePlaceholder": "Descreva a oferta ou novidade (10–280 caracteres)",
    "adImageOptional": "Imagem (opcional)",
    "adPreview": "Anúncio",
    "adsApprovalNote": "Anúncios passam por aprovação do admin e ficam ativos por 24h após aprovação.",
    "yourAds": "Seus anúncios",
    "adsRegisteredOne": "{count} cadastrado",
    "adsRegisteredMany": "{count} cadastrados",
    "createFirstAd": "Crie seu primeiro anúncio usando o formulário acima.",
    "waitStoreApproval": "Aguarde a aprovação da loja para começar.",
    "settingsSubtitle": "Dados e aparência da sua loja",
    "storeInfo": "Informações da loja",
    "openingHours": "Horário",
    "openingHoursPlaceholder": "Ex: Seg–Sex 9h–18h",
    "instagram": "Instagram",
    "instagramPlaceholder": "@minhaloja ou instagram.com/minhaloja",
    "instagramOptionalHint": "Opcional — aparece na vitrine pública da sua loja.",
    "themeColor": "Cor do tema",
    "paymentMethods": "Formas de pagamento",
    "paymentMethodsHint": "Escolha quais opções o cliente vê ao finalizar o pedido no carrinho.",
    "accountSubtitle": "Altere sua senha de acesso ao painel",
    "statusPendingBanner": "Sua loja está em análise. Você já pode cadastrar produtos; a vitrine pública ficará visível após aprovação.",
    "statusApprovedBanner": "Sua loja está ativa no marketplace.",
    "statusBlockedBanner": "Sua loja está bloqueada. Entre em contato com o suporte para mais informações.",
    "planPriceLabel": "{price} · Ver planos",
    "noAdsTitle": "Nenhum anúncio",
    "planRenewalWarningTitle": "Plano prestes a vencer",
    "planRenewalWarningBody": "Seu plano {planName} vence em {remaining} ({date}). Renove agora para manter sua loja visível no marketplace.",
    "planRenewalExpiredTitle": "Plano vencido",
    "planRenewalExpiredBody": "Seu plano {planName} venceu em {date}. Sem renovação, sua loja volta ao plano Gratuito e apenas os 2 produtos mais recentes permanecem ativos.",
    "planRenewalWarningHint": "Se o plano não for renovado, sua loja volta ao Gratuito e só os 2 últimos produtos adicionados ficam ativos.",
    "planDowngradedTitle": "Plano Gratuito reativado",
    "planDowngradedBody": "Seu plano pago expirou. Você está no plano Gratuito e apenas os 2 produtos mais recentes permanecem ativos no catálogo. Renove para reativar os demais.",
    "planRenewalCta": "Renovar plano",
    "planExpiresOn": "Vence em {date}"
  },
  "planRenewal": {
    "expiredNow": "agora",
    "hoursRemainingOne": "{hours} hora",
    "hoursRemainingMany": "{hours} horas",
    "daysRemainingOne": "{days} dia",
    "daysRemainingMany": "{days} dias"
  },
  "admin": {
    "restrictedAccess": "Acesso restrito",
    "overviewSubtitle": "Resumo multi-bairro da plataforma e atalhos rápidos",
    "quickNewStore": "Nova loja",
    "quickNeighborhoods": "Bairros",
    "quickModerators": "Moderadores",
    "metricStores": "Lojas",
    "metricProducts": "Produtos",
    "metricOrders": "Pedidos",
    "metricRevenue": "Receita",
    "metricViews": "Visualizações",
    "metricPending": "Pendentes",
    "allCaughtUpTitle": "Tudo em dia",
    "allCaughtUpBody": "Nenhuma loja ou pedido de plano aguardando aprovação.",
    "neighborhoodCreated": "Bairro criado",
    "neighborhoodUpdated": "Bairro atualizado",
    "categoryCreated": "Categoria criada",
    "categoryUpdated": "Categoria atualizada",
    "marketplaceCategories": "Tipos do marketplace",
    "categoriesSubtitle": "Crie e edite as categorias (tags de tipo) que lojistas escolhem no cadastro e no catálogo",
    "categoriesHint": "Só o admin gerencia a lista. Lojistas apenas selecionam uma opção existente.",
    "newCategory": "Nova categoria",
    "createCategory": "Criar categoria",
    "registeredCategories": "Categorias cadastradas",
    "categoriesCount": "{count} categoria(s)",
    "noCategoriesTitle": "Nenhuma categoria",
    "createFirstCategory": "Crie a primeira categoria para classificar lojas e produtos.",
    "categoryNamePlaceholder": "Ex.: Alimentação, Moda, Serviços",
    "categoryHasStores": "Há {count} loja(s) nesta categoria",
    "categoryHasProducts": "Há {count} produto(s) nesta categoria",
    "deleteCategoryPermanent": "Excluir categoria permanentemente",
    "saveCategory": "Salvar categoria",
    "thisCategory": "esta categoria",
    "confirmDeleteCategory": "Excluir a categoria \"{name}\"? Esta ação não pode ser desfeita.",
    "moderatorPermissionsUpdated": "Permissões do moderador atualizadas",
    "promoteModerator": "Promover a moderador",
    "regionScope": "Região: {name}",
    "planRenewalAlertsTitle": "Planos a renovar",
    "planRenewalExpiredChip": "{count} vencido(s)",
    "planRenewalWarningChip": "{count} vencendo em breve",
    "planRenewalExpiredCard": "Plano {planName} vencido em {date} — voltará ao Gratuito (2 produtos ativos)",
    "planRenewalWarningCard": "Plano {planName} vence em {remaining} ({date})",
    "planRenewalNoPendingRequest": "Sem pedido de renovação enviado",
    "planChangeRequestsTitle": "Pedidos de mudança de plano",
    "planChangeStoreId": "ID da loja",
    "merchant": "Lojista",
    "approvePlan": "Aprovar plano",
    "neighborhoodsAndModerators": "Bairros e moderadores",
    "manageNeighborhoods": "Gerenciar bairros",
    "manageModerators": "Gerenciar moderadores",
    "activeNeighborhoodsChip": "{count} bairro(s) ativo(s)",
    "totalRegionsChip": "{count} região(ões) no total",
    "moderatorsChip": "{count} moderador(es)",
    "unassignedStoresChip": "{count} loja(s) sem bairro",
    "noNeighborhoodsTitle": "Nenhum bairro",
    "noNeighborhoodsBody": "Cadastre regiões para segmentar lojas e moderadores.",
    "createNeighborhood": "Criar bairro",
    "allNeighborhoods": "Todos os bairros",
    "allStores": "Todas as lojas",
    "searchOrdersPlaceholder": "Buscar cliente, telefone ou loja...",
    "totalOrders": "Total de pedidos",
    "accumulatedRevenue": "Receita acumulada",
    "chartOrdersTooltip": "{label}: {count} pedido(s)",
    "chartRevenueTooltip": "{label}: {value}",
    "ordersByPeriod": "Pedidos por período",
    "periodOrdersSummary": "{count} pedido(s) · {revenue} no período",
    "ordersChartAria": "Gráfico de pedidos por período",
    "noOrdersRegistered": "Nenhum pedido registrado",
    "logo": "Logo",
    "removeCurrentLogo": "Remover logo atual",
    "banner": "Banner",
    "removeCurrentBanner": "Remover banner atual",
    "noProductsInStore": "Nenhum produto nesta loja",
    "saveProduct": "Salvar produto",
    "searchStorePlaceholder": "Buscar loja...",
    "noStoresRegistered": "Nenhuma loja cadastrada",
    "noStoresSearchMatch": "Nenhuma loja encontrada para esta busca.",
    "productCount": "{count} produto(s)",
    "selectStoreTitle": "Selecione uma loja",
    "selectStoreBody": "Escolha uma loja na lista ao lado para ver os produtos.",
    "newItemInStore": "+ Novo item em {name}",
    "productImage": "Imagem do produto",
    "newProduct": "Novo produto",
    "createItem": "Criar item",
    "storeNotApprovedHint": "Esta loja ainda não está aprovada. Aprove-a em Aprovações para cadastrar novos produtos.",
    "searchProductPlaceholder": "Buscar produto...",
    "quickNewStoreDesc": "Cadastrar vitrine",
    "addToCatalog": "Adicionar ao catálogo",
    "marketplaceRegions": "Regiões do marketplace",
    "regionalTeam": "Equipe regional",
    "ordersMetricsHistory": "Métricas e histórico",
    "registrationsAndPlans": "Cadastros e planos",
    "viewSite": "Ver site",
    "stringsEditor": "Editor de textos",
    "stringsEditorDesc": "Editar textos da interface (strings.js)",
    "openMarketplace": "Abrir marketplace",
    "noOrdersTitle": "Nenhum pedido",
    "noOrdersOnPlatform": "Nenhum pedido foi registrado na plataforma ainda.",
    "storeStatusTitle": "Status das lojas",
    "viewStores": "Ver lojas",
    "manageStores": "Gerenciar lojas",
    "recentApprovals": "Aprovações recentes",
    "viewAllPending": "Ver todas ({count})",
    "pendingIssues": "{count} pendência(s)",
    "pendingAwaitingReview": "{count} pendência(s) aguardando sua revisão",
    "emptyQueueTitle": "Fila vazia",
    "emptyQueueBody": "Nenhuma loja, anúncio ou pedido de plano aguardando aprovação.",
    "storeAdsApprovalsTitle": "Anúncios de loja",
    "approveAd": "Aprovar anúncio",
    "adApproved": "Anúncio aprovado",
    "adRejected": "Anúncio rejeitado",
    "confirmRejectAd": "Rejeitar este anúncio?",
    "adExtraFee": "Taxa extra",
    "adDurationHours": "{hours}h de exibição após aprovação",
    "adId": "ID do anúncio",
    "adsSubtitle": "Crie, edite e exclua anúncios do feed",
    "adsTotal": "{count} anúncio(s)",
    "newAd": "Novo anúncio",
    "createAd": "Criar anúncio",
    "confirmDeleteAd": "Excluir este anúncio permanentemente?",
    "adDeleted": "Anúncio excluído",
    "adCreated": "Anúncio criado",
    "adUpdated": "Anúncio atualizado",
    "publishAdImmediately": "Publicar imediatamente (ativo por 24h)",
    "selectStoreForAd": "Loja",
    "noAdsTitle": "Nenhum anúncio",
    "noAdsBody": "Crie o primeiro anúncio usando o formulário acima.",
    "searchAdsPlaceholder": "Buscar anúncio ou loja...",
    "staffAdsHint": "Admin e moderador podem criar anúncios sem limite de plano. Publicados ficam ativos por 24h após aprovação.",
    "adTitlePlaceholder": "Título do anúncio",
    "adMessagePlaceholder": "Mensagem do anúncio",
    "adImageOptional": "Imagem (opcional)",
    "storeRegistrations": "Cadastros de loja",
    "pendingChip": "{count} pendente(s)",
    "approveStore": "Aprovar loja",
    "storesInRegion": "{count} loja(s) na região",
    "storesReadOnly": "{count} loja(s) — somente leitura",
    "storesRegistered": "{count} loja(s) cadastradas",
    "noMerchantsHint": "Nenhum lojista cadastrado. Crie contas em <a href=\"#/lojista/cadastro\">Área do Lojista</a> primeiro.",
    "newStoreSummary": "+ Nova loja",
    "responsibleMerchant": "Lojista responsável",
    "openingHours": "Horário",
    "themeColor": "Cor do tema",
    "planFree": "Gratuito",
    "publishStoreImmediately": "Publicar loja imediatamente (aprovada e ativa)",
    "createStore": "Criar loja",
    "searchStoresNeighborhood": "Buscar loja, bairro, lojista ou telefone...",
    "searchStoresCity": "Buscar loja, cidade ou lojista...",
    "noStoresTitle": "Nenhuma loja",
    "noStoresBody": "Cadastre a primeira loja usando o formulário acima.",
    "instagram": "Instagram",
    "saveStore": "Salvar loja",
    "productsReadOnly": "Produtos de {name} — somente leitura",
    "managingProducts": "Gerenciando produtos de {name}",
    "productsAcrossStores": "{products} produto(s) em {stores} loja(s)",
    "readonlyProductsHint": "Moderadores podem visualizar produtos, mas não criar nem editar.",
    "ordersSalesSubtitle": "{count} pedido(s) · {revenue} em vendas",
    "noOrdersBody": "Os pedidos feitos pelos clientes aparecerão aqui.",
    "exportFilteredHint": "Exporta todos os pedidos filtrados (todas as páginas)",
    "neighborhoodsSubtitle": "Cadastre bairros e regiões para filtrar o marketplace e escopar moderadores",
    "newNeighborhood": "Novo bairro",
    "registeredNeighborhoods": "Bairros cadastrados",
    "regionsCount": "{count} região(ões)",
    "createFirstNeighborhood": "Crie o primeiro bairro para segmentar lojas e moderadores.",
    "neighborhoodHasStores": "Há {count} loja(s) neste bairro",
    "neighborhoodHasModerators": "Há {count} moderador(es) neste bairro",
    "deleteNeighborhoodPermanent": "Excluir bairro permanentemente",
    "slugAutoUpdateHint": "O slug da URL é atualizado automaticamente ao salvar o nome.",
    "saveNeighborhood": "Salvar bairro",
    "moderatorsSubtitle": "Promova usuários, defina o bairro e configure as permissões de cada moderador",
    "promoteUser": "Promover usuário",
    "promoteUserHint": "O usuário precisa já ter conta como cliente ou lojista. Escolha <strong>Todos os bairros</strong> para moderar a plataforma inteira, ou um bairro específico. Após a promoção, ele acessa em <a href=\"#/moderador/entrar\">#/moderador/entrar</a>.",
    "userEmail": "Email do usuário",
    "activeModerators": "Moderadores ativos",
    "moderatorsRegistered": "{count} cadastrado(s)",
    "moderatorsPermissionsHint": "Todos aprovam cadastros de loja do bairro. Use <strong>Permissões</strong> para liberar mudanças de plano e alterar a região.",
    "noModeratorsTitle": "Nenhum moderador",
    "noModeratorsBody": "Promova o primeiro usuário usando o formulário acima.",
    "searchModeratorsPlaceholder": "Buscar por nome ou email...",
    "noModeratorsFilter": "Nenhum moderador corresponde à busca.",
    "sortNameAsc": "Ordenar por nome, A–Z",
    "sortNameDesc": "Ordenar por nome, Z–A",
    "sortEmailAsc": "Ordenar por email, A–Z",
    "sortEmailDesc": "Ordenar por email, Z–A",
    "noNeighborhoodAssigned": "Sem bairro",
    "removeAccess": "Remover acesso",
    "permissionsOf": "Permissões de {name}",
    "extraPermissions": "Permissões extras",
    "storeApprovalAlwaysAllowed": "Aprovação de cadastro de loja é sempre permitida no bairro atribuído.",
    "savePermissions": "Salvar permissões",
    "moderatorsFiltered": "{matched} de {total} moderador(es)",
    "accountSubtitleAdmin": "Altere seu email e senha de acesso ao painel",
    "accountSubtitleModerator": "Altere sua senha de acesso ao painel",
    "changeEmail": "Alterar email",
    "newEmail": "Novo email",
    "emailConfirmationHint": "Enviaremos um link de confirmação para o novo endereço.",
    "regionLabel": "Região:",
    "regionNotAssignedAdmin": "Não atribuída — contate o administrador",
    "changePassword": "Alterar senha",
    "csvTotal": "Total (R$)",
    "createProduct": "Criar produto",
    "storeCreatedNamed": "Loja \"{name}\" criada!",
    "storeUpdated": "Loja atualizada!",
    "itemCreated": "Item criado!",
    "itemUpdated": "Item atualizado!",
    "confirmDeleteProduct": "Excluir este produto?",
    "productDeleted": "Produto excluído",
    "productDeactivated": "Produto desativado (há pedidos vinculados)",
    "productDeleteError": "Não foi possível excluir o produto.",
    "confirmDeleteStore": "Excluir a loja \"{name}\" e todos os produtos, pedidos e dados vinculados? Esta ação não pode ser desfeita.",
    "storeDeleted": "Loja excluída",
    "storeDeleteError": "Não foi possível excluir a loja.",
    "profilesSubtitle": "Gerenciar contas de clientes, lojistas e moderadores",
    "profilesHint": "Excluir um perfil remove a conta de acesso e os dados vinculados. Administradores e sua própria conta não podem ser excluídos por aqui.",
    "searchProfilesPlaceholder": "Buscar por nome ou e-mail...",
    "noProfilesTitle": "Nenhum perfil",
    "noProfilesBody": "Não há usuários cadastrados na plataforma.",
    "roleModerator": "Moderador",
    "roleAdmin": "Administrador",
    "profileProtected": "Protegido",
    "confirmDeleteProfile": "Excluir permanentemente o perfil de {name}? Esta ação não pode ser desfeita.",
    "profileDeleted": "Perfil excluído",
    "profileDeleteError": "Não foi possível excluir o perfil.",
    "neighborhoodActivated": "Bairro ativado",
    "neighborhoodDeactivated": "Bairro desativado",
    "thisNeighborhood": "este bairro",
    "confirmDeleteNeighborhood": "Excluir o bairro \"{name}\"? Esta ação não pode ser desfeita.",
    "promoting": "Promovendo...",
    "userPromotedToModerator": "{name} agora é moderador",
    "confirmRemoveModerator": "Remover acesso de moderador de {name}?",
    "moderatorAccessRemoved": "Acesso de moderador removido",
    "confirmNewEmail": "Confirme o novo email em <strong>{email}</strong> pelo link enviado.",
    "confirmationLinkSent": "Link de confirmação enviado!",
    "emailChangedSuccess": "Email alterado com sucesso.",
    "emailUpdated": "Email atualizado!",
    "passwordsMismatch": "As senhas não coincidem.",
    "passwordChangedSuccess": "Senha alterada com sucesso.",
    "storeApproved": "Loja aprovada!",
    "confirmRejectStore": "Rejeitar esta loja?",
    "storeRejected": "Loja rejeitada",
    "planApproved": "Plano aprovado!",
    "confirmRejectPlanChange": "Rejeitar este pedido de mudança de plano?",
    "planChangeRejected": "Pedido de plano rejeitado",
    "whatsappPlaceholder": "5521999999999",
    "openingHoursPlaceholder": "Seg–Sáb 8h–20h",
    "instagramPlaceholder": "@minhaloja",
    "neighborhoodNamePlaceholder": "Copacabana",
    "cityPlaceholder": "Rio de Janeiro",
    "userEmailPlaceholder": "usuario@email.com",
    "emailPlaceholder": "seu@email.com",
    "reportsTitle": "Denúncias de conteúdo",
    "reportsSubtitle": "{count} denúncia(s) aguardando análise",
    "reportsEmptyTitle": "Nenhuma denúncia pendente",
    "reportsEmptyBody": "Quando clientes ou lojistas denunciarem lojas ou produtos, elas aparecerão aqui.",
    "reportTypeStore": "Loja",
    "reportTypeProduct": "Produto",
    "reportedBy": "Denunciado por",
    "reportReason": "Motivo",
    "reportDetails": "Comentário",
    "reportReviewNote": "Nota da análise (opcional)",
    "reportResolve": "Resolver",
    "reportDismiss": "Arquivar",
    "reportResolved": "Denúncia resolvida",
    "reportDismissed": "Denúncia arquivada",
    "reportReviewError": "Não foi possível atualizar a denúncia.",
    "viewReportedStore": "Ver loja"
  },
  "report": {
    "title": "Denunciar conteúdo",
    "button": "Denunciar",
    "reasonLabel": "Motivo",
    "reasonPlaceholder": "Selecione um motivo",
    "reasonInappropriate": "Conteúdo impróprio ou inadequado",
    "reasonMisleading": "Informação enganosa ou preço incorreto",
    "reasonCounterfeit": "Produto falso, pirata ou proibido",
    "reasonScam": "Golpe, fraude ou tentativa de enganar",
    "reasonSpam": "Spam ou propaganda abusiva",
    "reasonOffensive": "Ofensivo, discriminatório ou assédio",
    "reasonCopyright": "Uso indevido de imagem ou marca",
    "reasonPrivacy": "Violação de privacidade ou dados pessoais",
    "reasonOther": "Outro motivo",
    "detailsLabel": "Comentário",
    "detailsPlaceholder": "Explique o que está errado e por que denuncia",
    "detailsHint": "Sua denúncia será analisada por admin ou moderador da região.",
    "submit": "Enviar denúncia",
    "submitted": "Denúncia enviada. Obrigado pelo retorno.",
    "submitError": "Não foi possível enviar a denúncia.",
    "loginRequired": "Faça login para denunciar.",
    "targetStore": "Denunciando a loja: {name}",
    "targetProduct": "Denunciando o produto: {name}"
  },
  "moderator": {
    "panelLabel": "Painel Moderador",
    "regionNotAssigned": "Região não atribuída — contate o admin",
    "readonlyStoresHint": "Moderadores podem visualizar lojas, mas não criar nem editar.",
    "approvalOnlyBadge": "Somente aprovações de loja",
    "approvePlanChanges": "Aprovar mudanças de plano",
    "approvePlanChangesDesc": "Analisa pedidos de upgrade ou downgrade de plano das lojas do bairro atribuído."
  },
  "errors": {
    "generic": "Não foi possível concluir a operação. Tente novamente.",
    "invalidCredentials": "Email ou senha incorretos. Verifique os dados ou use \"Esqueci minha senha\".",
    "informNeighborhoodName": "Informe o nome do bairro.",
    "selectModeratorNeighborhood": "Selecione o bairro do moderador.",
    "minAgeRegistration": "É necessário ter 18 anos ou mais para criar conta.",
    "birthDateRequired": "Informe sua data de nascimento.",
    "birthDateInvalid": "Data de nascimento inválida.",
    "minAgeRegistrationWithAge": "É necessário ter {age} anos ou mais para se cadastrar.",
    "instagramInvalid": "Usuário do Instagram inválido. Use letras, números, ponto ou underscore (até 30 caracteres).",
    "googleProviderDisabled": "Login com Google não está ativado no Supabase. Habilite em Authentication → Providers → Google (Client ID e Secret do Google Cloud).",
    "emailNotConfirmed": "Confirme seu email antes de entrar.",
    "emailAlreadyInUse": "Este email já está em uso.",
    "invalidEmail": "Email inválido.",
    "informNewEmail": "Informe o novo email.",
    "sessionExpired": "Sessão expirada. Entre novamente.",
    "emailAlreadyCurrent": "Este já é o seu email atual.",
    "informCity": "Informe a cidade.",
    "stateMustBe2Letters": "UF deve ter 2 letras.",
    "noChanges": "Nenhuma alteração informada.",
    "invalidNeighborhood": "Bairro inválido.",
    "cannotDeleteNeighborhoodStores": "Não é possível excluir: {count} loja(s) vinculada(s). Mova as lojas para outro bairro antes.",
    "cannotDeleteNeighborhoodModerators": "Não é possível excluir: {count} moderador(es) vinculado(s). Reatribua-os em Moderadores antes.",
    "userNotModerator": "Usuário não é moderador.",
    "selectStoreNeighborhood": "Selecione o bairro da loja.",
    "selectStoreCategory": "Selecione a categoria da loja.",
    "informStoreName": "Informe o nome da loja.",
    "storeNameTaken": "Já existe uma loja com este nome (ou slug). Escolha outro nome.",
    "informCategoryName": "Informe o nome da categoria.",
    "invalidCategory": "Categoria inválida.",
    "cannotDeleteCategoryStores": "Não é possível excluir: {count} loja(s) vinculada(s). Reatribua as lojas antes.",
    "cannotDeleteCategoryProducts": "Não é possível excluir: {count} produto(s) vinculado(s). Reatribua os produtos antes.",
    "neighborhoodInactive": "Este bairro está inativo. Escolha outro bairro ativo.",
    "engagementUnavailable": "Recurso de curtidas/comentários indisponível. Rode a migration 011 no Supabase.",
    "commentRequired": "Escreva um comentário antes de enviar.",
    "commentTooLong": "O comentário deve ter no máximo 500 caracteres.",
    "informName": "Informe seu nome.",
    "informPhone": "Informe seu telefone.",
    "informAddress": "Informe seu endereço.",
    "selectDeliveryPeriod": "Selecione um horário de entrega.",
    "informUserEmail": "Informe o email do usuário.",
    "userNotFound": "Usuário não encontrado. A pessoa precisa ter uma conta no site.",
    "cannotChangeAdminRole": "Não é possível alterar o papel de um administrador.",
    "userAlreadyModerator": "Este usuário já é moderador.",
    "noPermissionsInformed": "Nenhuma permissão informada.",
    "loginRequiredForPlan": "Faça login para solicitar um plano.",
    "noPermissionPlanRequest": "Sem permissão para solicitar plano desta loja.",
    "invalidPlan": "Plano inválido.",
    "planAlreadyCurrent": "Este já é o seu plano atual.",
    "planRequestPending": "Já existe um pedido de plano aguardando aprovação.",
    "planRequestAlreadyReviewed": "Este pedido já foi analisado.",
    "storeAdsPremiumOnly": "Anúncios no feed são exclusivos do plano Premium.",
    "storeAdsMonthlyLimit": "Limite de {limit} anúncios por mês no plano Premium. Aguarde o próximo mês ou entre em contato com o suporte.",
    "storeAdNotPending": "Este anúncio não está mais aguardando aprovação.",
    "storeAdFeeAckRequired": "Confirme a taxa de {fee} para criar um anúncio extra.",
    "cannotLikeOwnProduct": "Você não pode curtir produtos da sua própria loja.",
    "cannotFavoriteOwnStore": "Você não pode favoritar a sua própria loja.",
    "cannotReportOwnStore": "Você não pode denunciar a sua própria loja.",
    "cannotReportOwnProduct": "Você não pode denunciar produtos da sua própria loja.",
    "reportReasonRequired": "Selecione um motivo válido para a denúncia.",
    "reportDetailsRequired": "Escreva um comentário explicando a denúncia.",
    "reportDetailsTooLong": "O comentário deve ter no máximo 500 caracteres.",
    "reportsUnavailable": "Denúncias indisponíveis. Rode a migration 042 no Supabase.",
    "reportAlreadyPending": "Você já tem uma denúncia pendente para este conteúdo.",
    "invalidReportStatus": "Status de denúncia inválido.",
    "storeNotFound": "Loja não encontrada.",
    "productNotFound": "Produto não encontrado."
  },
  "uploads": {
    "logoHint": "JPG, PNG, WebP ou GIF — máx. 500 kb.",
    "bannerHint": "JPG, PNG, WebP ou GIF — planos pagos, máx. 500 kb .",
    "productHint": "JPG, PNG, WebP ou GIF — máx. {maxKb} KB.",
    "invalidImage": "Selecione um arquivo de imagem válido.",
    "unsupportedFormat": "Formato não suportado. Use JPG, PNG, WebP ou GIF.",
    "imageTooLarge": "Imagem muito grande. Máximo {max}."
  },
  "labels": {
    "name": "Nome",
    "email": "Email",
    "password": "Senha",
    "phone": "Telefone",
    "openingHours": "Horário",
    "instagram": "Instagram",
    "themeColor": "Cor do tema",
    "active": "Ativo",
    "priceHistory": "Histórico de preços",
    "address": "Endereço",
    "birthDate": "Data de nascimento",
    "storeName": "Nome da loja",
    "neighborhoodRegion": "Bairro / região",
    "category": "Categoria",
    "whatsapp": "WhatsApp",
    "description": "Descrição",
    "city": "Cidade",
    "state": "UF",
    "status": "Status",
    "plan": "Plano",
    "permissions": "Permissões",
    "newPassword": "Nova senha",
    "confirmNewPassword": "Confirmar nova senha",
    "save": "Salvar",
    "cancel": "Cancelar",
    "close": "Fechar",
    "edit": "Editar",
    "delete": "Excluir",
    "approve": "Aprovar",
    "reject": "Rejeitar",
    "note": "Observação"
  },
  "toasts": {
    "panelUpdated": "Painel atualizado",
    "orderSent": "Pedido enviado! Confirme no WhatsApp.",
    "storeCreated": "Loja criada!",
    "neighborhoodDeleted": "Bairro excluído",
    "categoryDeleted": "Categoria excluída",
    "noOrdersToExport": "Nenhum pedido para exportar"
  },
  "pagination": {
    "previous": "← Anterior",
    "next": "Próxima →",
    "pageStatus": "Página {current} de {total}",
    "ordersCount": "{count} pedido(s)",
    "moderatorSingular": "moderador",
    "moderatorPlural": "moderadores",
    "itemSingular": "item",
    "itemPlural": "itens",
    "storeSingular": "loja",
    "storePlural": "lojas",
    "cardSingular": "card",
    "cardPlural": "cards",
    "orderSingular": "pedido",
    "orderPlural": "pedidos",
    "rangeOf": "{start}–{end} de {count} {label}"
  },
  "storeStatus": {
    "pending": "Pendente",
    "approved": "Aprovada",
    "blocked": "Bloqueada",
    "active": "Ativo",
    "inactive": "Inativo",
    "approvedCount": "{count} aprovadas",
    "pendingCount": "{count} pendentes",
    "blockedCount": "{count} bloqueadas",
    "approvedPlural": "Aprovadas",
    "pendingPlural": "Pendentes",
    "blockedPlural": "Bloqueadas"
  },
  "deliveryPeriod": {
    "morning": "Manhã",
    "afternoon": "Tarde",
    "evening": "Noite",
    "dawn": "Madrugada"
  },
  "router": {
    "notFoundTitle": "Página não encontrada",
    "notFoundBack": "Voltar ao início"
  },
  "catalog": {
    "product": "Produto",
    "service": "Serviço",
    "type": "Tipo",
    "stock": "Estoque",
    "onRequest": "Sob consulta",
    "used": "Usado"
  },
  "rules": {
    "title": "Regras da Plataforma",
    "section1Title": "1. Sobre o MaredeVendas",
    "section1Body": "Marketplace local que conecta clientes a lojas da região. Pedidos são finalizados via WhatsApp — não há pagamento in-app.",
    "section2Title": "2. Clientes",
    "section2Item1": "Não é obrigatório criar conta para comprar.",
    "section2Item2": "Conta gratuita permite favoritar lojas e pré-preencher dados no checkout.",
    "section2Item3": "Combine entrega e pagamento diretamente com a loja no WhatsApp.",
    "section3Title": "3. Lojistas",
    "section3Item1": "Cadastro sujeito à aprovação do administrador.",
    "section3Item2": "Informações da loja devem ser verdadeiras e atualizadas.",
    "section3Item3": "Produtos com preço e estoque corretos.",
    "section3Item4": "WhatsApp deve estar ativo para receber pedidos.",
    "section4Title": "4. Planos para lojistas",
    "section4Body": "Escolha o plano que melhor se encaixa no tamanho da sua loja. O plano Gratuito é ativado após aprovação do cadastro. Para planos pagos, solicite a mudança no painel da loja após o login.",
    "section4HowToTitle": "Como assinar um plano pago:",
    "section4Step1": "Entre no painel da loja em Planos.",
    "section4Step2": "Realize o pagamento do valor mensal do plano escolhido.",
    "section4Step3": "Solicite o plano e envie o comprovante pelo WhatsApp.",
    "section4Step4": "Após confirmação, seu plano será ativado pelo administrador.",
    "section5Title": "5. Conduta",
    "section5Body": "Conteúdo ilegal, discriminatório ou enganoso será removido. Lojas podem ser bloqueadas em caso de violação."
  },
  "plans": {
    "priceChangeAnytime": "Alteração de preços a qualquer momento",
    "priceChangeEveryHours": "Alteração de preços a cada {hours}h",
    "priceChangeEveryDays": "Alteração de preços a cada {days} dia(s)",
    "freeBannerMessage": "O plano Gratuito não inclui banner personalizado. Assine um plano pago para personalizar o banner da vitrine.",
    "freeProductImageMessage": "O plano Gratuito não permite imagens nos produtos. Assine um plano pago para enviar fotos no catálogo.",
    "productLimitMessage": "O plano {plan} permite até {limit} itens no catálogo (produtos e serviços). Assine um plano superior para ampliar.",
    "productImageLimitMessage": "O plano {plan} permite imagens em até {limit} produto(s). Assine um plano superior para liberar mais.",
    "productLimitHint": "{plan}: {count}/{limit} itens no catálogo",
    "productLimitRemaining": " — restam {remaining}",
    "productImageLimitHint": "{plan}: {count}/{limit} produtos com imagem",
    "planFree": "Gratuito",
    "planFreeDesc": "Para testar a vitrine com catálogo enxuto.",
    "planPlusDesc": "Catálogo inicial com branding e mais flexibilidade de preços.",
    "planPremiumDesc": "Catálogo ampliado para lojas consolidadas.",
    "includedOnApproval": "Incluso na aprovação do cadastro",
    "requestRenewal": "Solicitar renovação",
    "sendReceiptWhatsapp": "Enviar comprovante no WhatsApp",
    "yourCurrentPlan": "Seu plano atual",
    "renewPlan": "Renovar — {plan}",
    "requestPlan": "Solicitar — {plan}",
    "subscribePlan": "Assinar — {plan}",
    "sendReceiptPlan": "Enviar comprovante — {plan}",
    "paymentWhatsappGreeting": "Olá!",
    "paymentWhatsappBody": "Sou lojista do MaredeVendas e quero assinar o plano *{plan}*{price}.",
    "paymentWhatsappBodyWithStore": "Sou lojista do MaredeVendas, da loja *{storeName}*, e quero assinar o plano *{plan}*{price}.",
    "paymentWhatsappReceipt": "Segue o comprovante de pagamento em anexo.",
    "paymentWhatsappStoreId": "ID da loja: {id}",
    "paymentWhatsappStoreName": "Nome da loja: {name}",
    "paymentWhatsappStoreNameBlank": "Nome da loja:",
    "paymentWhatsappEmail": "Email cadastrado:",
    "planRequestStoreNote": "Loja: {storeName} · ID: {storeId}",
    "paymentWhatsappPlanPlaceholder": "(informar plano)",
    "featureFreeItems2": "Até 2 itens (produtos ou serviços)",
    "featureFreeNoImages": "Sem imagens nos produtos (planos pagos liberam fotos)",
    "featureFreeOneImage": "1 foto no catálogo (planos pagos liberam mais)",
    "featureStoreLogo": "Logo da loja (foto de perfil)",
    "featureDefaultBanner": "Banner padrão por cor (sem banner personalizado)",
    "featureToggleProducts": "Ativar ou ocultar produtos à venda",
    "featureWhatsappOrders": "Pedidos via WhatsApp",
    "featurePlusItems6": "Até 6 itens (produtos ou serviços)",
    "featurePlusImages6": "Imagens em até 6 produtos (500 KB cada)",
    "featureCustomBanner": "Banner personalizado da vitrine",
    "featureHomeHighlight": "Destaque visual na página inicial",
    "featurePlusImagesAll": "Imagens em todos os produtos (500 KB cada)",
    "featureSearchPriority": "Prioridade nas buscas",
    "featurePremiumItems30": "Até 30 itens (produtos ou serviços)",
    "featurePremiumAds2": "Até 2 anúncios por mês na aba Anúncios",
    "featurePremiumAdsRotation24h": "Rotação de prioridade dos anúncios a cada 24h",
    "featureFeedRotation24h": "Rotação de prioridade no feed a cada 24h",
    "premiumAdsOnlyMessage": "Anúncios no feed são exclusivos do plano Premium.",
    "monthlyAdLimitMessage": "Limite de {limit} anúncios por mês no plano Premium.",
    "monthlyAdLimitHint": "Premium: {count}/{limit} anúncios inclusos neste mês ({remaining} restante(s)).",
    "extraAdFeeHint": "Anúncios extras: {fee} cada, {hours}h de exibição após aprovação.",
    "extraAdPaymentBody": "Sou lojista do MaredeVendas e quero publicar um *anúncio extra* no feed ({fee}, {hours}h após aprovação).",
    "extraAdPaymentTitle": "Título do anúncio: {title}",
    "extraAdPaymentId": "ID do anúncio: {id}",
    "planPlus": "Plus",
    "planPremium": "Premium",
    "cooldownRemainingHours": "{hours}h {minutes}min",
    "cooldownRemainingMinutes": "{minutes}min"
  },
  "whatsapp": {
    "greeting": "Olá!",
    "orderIntro": "Gostaria de fazer o seguinte pedido (produtos e/ou serviços):",
    "lineItem": "{kind}: {name} ({qty}x) - {price}",
    "total": "Total: {amount}",
    "paymentMethod": "Forma de pagamento: {method}",
    "customerName": "Nome: {name}",
    "customerPhone": "Telefone: {phone}",
    "addressLabel": "Endereço:",
    "deliveryPeriod": "Melhor horário para entrega: {period}",
    "thanks": "Obrigado."
  }
}

/** Resolve chave pontuada (ex.: nav.home) e substitui {placeholders}. */
export function t(key, vars = {}) {
  const value = key.split('.').reduce((obj, part) => obj?.[part], STRINGS)
  if (typeof value !== 'string') return key
  return value.replace(/\{(\w+)\}/g, (_, name) => String(vars[name] ?? `{${name}}`))
}

const DELIVERY_PERIOD_KEYS = {
  manha: 'deliveryPeriod.morning',
  tarde: 'deliveryPeriod.afternoon',
  noite: 'deliveryPeriod.evening',
  madrugada: 'deliveryPeriod.dawn',
}

export function deliveryPeriodLabel(period) {
  return t(DELIVERY_PERIOD_KEYS[period] ?? period)
}

const ORDER_STATUS_KEYS = {
  pending: 'orderStatus.pending',
  sent: 'orderStatus.sent',
  viewed: 'orderStatus.viewed',
}

export function orderStatusLabel(status) {
  return t(ORDER_STATUS_KEYS[status] ?? status)
}

export function flattenStrings(obj = STRINGS, prefix = '') {
  const rows = []
  for (const [key, val] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key
    if (val && typeof val === 'object' && !Array.isArray(val)) {
      rows.push(...flattenStrings(val, path))
    } else {
      rows.push({ key: path, value: String(val ?? '') })
    }
  }
  return rows
}

export function unflattenStrings(rows) {
  const root = {}
  for (const { key, value } of rows) {
    const parts = key.split('.')
    let node = root
    for (let i = 0; i < parts.length - 1; i++) {
      node[parts[i]] ??= {}
      node = node[parts[i]]
    }
    node[parts[parts.length - 1]] = value
  }
  return root
}

const STRINGS_FILE_HEADER = `/**
 * Textos estáticos da interface — edite em strings-editor.html
 * Uso: import { t } from './strings.js'  →  t('nav.home')
 */

`

const STRINGS_FILE_HELPERS = `
/** Resolve chave pontuada (ex.: nav.home) e substitui {placeholders}. */
export function t(key, vars = {}) {
  const value = key.split('.').reduce((obj, part) => obj?.[part], STRINGS)
  if (typeof value !== 'string') return key
  return value.replace(/\\{(\\w+)\\}/g, (_, name) => String(vars[name] ?? \`{\${name}}\`))
}

export function flattenStrings(obj = STRINGS, prefix = '') {
  const rows = []
  for (const [key, val] of Object.entries(obj)) {
    const path = prefix ? \`\${prefix}.\${key}\` : key
    if (val && typeof val === 'object' && !Array.isArray(val)) {
      rows.push(...flattenStrings(val, path))
    } else {
      rows.push({ key: path, value: String(val ?? '') })
    }
  }
  return rows
}

export function unflattenStrings(rows) {
  const root = {}
  for (const { key, value } of rows) {
    const parts = key.split('.')
    let node = root
    for (let i = 0; i < parts.length - 1; i++) {
      node[parts[i]] ??= {}
      node = node[parts[i]]
    }
    node[parts[parts.length - 1]] = value
  }
  return root
}
`

/** Gera o conteúdo completo de strings.js para download. */
export function serializeStringsModule(strings = STRINGS) {
  return `${STRINGS_FILE_HEADER}export const STRINGS = ${JSON.stringify(strings, null, 2)}\n${STRINGS_FILE_HELPERS}`
}
